config/routes.rb
Rmails::Application.routes.draw do

  devise_for :admin_users, :skip => :registrations

  resources :admin_users, :only => [:index, :create, :update]
  match 'admin_users/first' => 'admin_users#first',
             :as => 'first_admin_user'

  resources :domains do
    resources :users
    resources :aliases
  end

  match 'server' => 'server#index',
             :as => 'server'
  match 'server/config/:id' => 'server#property',
             :as => 'server_property'
  match 'server/save_config' => 'server#update',
             :as => 'server_update'

  match 'statistics' => 'statistics#index',
             :as => 'statistics'

  devise_scope :admin_user do
    root :to => "devise/sessions#new"
  end

end

app/controllers/aliases_controller.rb
class AliasesController < ApplicationController

  before_filter :find_alias, :only => [:update, :destroy]

  def update
    if @alias.update_attributes(params[:virtual_alias])
      render :json => {:id => @alias.id}
    else
      render :json => {:errors => @alias.errors}
    end
  rescue
    render :json => {:errors => t('unknown_error')}
  end

  def create
    @domain = current_admin_user.domain(params[:domain_id])
    @alias = @domain.virtual_aliases.build(params[:virtual_alias])
    if @alias.save
      render :json => {:id => @alias.id}
    else
      render :json => {:errors => @alias.errors}
    end
  rescue
    render :json => {:errors => t('unknown_error')}
  end

  def destroy
    @alias.destroy
    render :json => {:id => nil}
  rescue
    render :json => {:errors => t('unknown_error')}
  end



protected

  def find_alias
    @domain = current_admin_user.domain(params[:domain_id])
    @alias = @domain.virtual_aliases.where(:id => params[:id]).first
  end

end

app/views/aliases/_form.html.haml
= simple_form_for virtual_alias, :url => domain_aliases_path(@domain||'{domain_id}'), :method => :post do |f|

  = f.input :source, :label => t('.source'), :hint => t('.source_hint')

  %i.icon-hand-right

  = f.input :destination, :label => t('.destination'), :as => :text, :hint => t('.dest_hint')

  .actions
    = f.button :button, t('.submit'), :type => 'submit', :class => 'btn-primary right'
    = f.button :button, t('.reset'), :type => 'reset', :class => 'left'

app/views/aliases/_templates.html.haml
%script#aliass_each_EJS{"type" => "text/ejs"}
  :plain
    <% list (items, function(item, index) { %>
      <tr id="alias_<%= index %>">
  %td.tar
    :plain
      <%= item.source %>
  %td
    %b
      :plain
        @<%= domain_name %>
    %i.icon-hand-right
  %td
    :plain
      <%= item.destination %>
  %td.tar
    = link_to t(".edit"), edit_domain_alias_path('{domain_id}', '{id}'), :class => 'label edit-alias'
    = link_to "&times;".html_safe, domain_alias_path('{domain_id}', '{id}'), :class => 'rm-alias', :title => t(".delete")
  :plain
      </tr>
    <% }) %>

%script#aliass_tabr_EJS{"type" => "text/ejs"}
  %tr.new

%script#aliass_form_EJS{"type" => "text/ejs"}
  %td{:colspan => "4"}
    = render :partial => '/aliases/form', :locals => { :virtual_alias => alias_ejs_object }