config/routes.rb
Rmails::Application.routes.draw do

  devise_for :admin_users, :skip => :registrations

  resources :admin_users, :only => [:index, :create, :update]
  match 'admin_users/first' => 'admin_users#first',
             :as => 'first_admin_user'

  resources :domains do
    resources :users
    resources :aliases
  end

  match 'server' => 'server#index',
             :as => 'server'
  match 'server/config/:id' => 'server#property',
             :as => 'server_property'
  match 'server/save_config' => 'server#update',
             :as => 'server_update'

  match 'statistics' => 'statistics#index',
             :as => 'statistics'

  devise_scope :admin_user do
    root :to => "devise/sessions#new"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :find_user, :only => [:update, :destroy]

  def update
    if @user.change_data params[:virtual_user]
      render :json => {:id => @user.id}
    else
      render :json => {:errors => @user.errors}
    end
  rescue
    render :json => {:errors => t('unknown_error')}
  end

  def create
    @domain = current_admin_user.domain(params[:domain_id])
    @user = @domain.virtual_users.build(params[:virtual_user])
    if @user.save
      render :json => {:id => @user.id}
    else
      render :json => {:errors => @user.errors}
    end
  rescue
    render :json => {:errors => t('unknown_error')}
  end

  def destroy
    @user.destroy
    render :json => {:id => nil}
  rescue
    render :json => {:errors => t('unknown_error')}
  end

protected

  def find_user
    @domain = current_admin_user.domain(params[:domain_id])
    @user = @domain.virtual_users.where(:id => params[:id]).first
  end

end

app/views/users/_form.html.haml
= simple_form_for virtual_user, :url => domain_users_path(@domain||'{domain_id}'), :method => :post, :html => { :class => 'form-horizontal'} do |f|

  = f.input :name,     :label => t('.name')
  = f.input :email,     :label => t('.email')
  = f.input :password,  :label => t('.password')

  = f.input :quota_kb,  :label => t('.quota_kb'), :hint => t('.no_limit')
  = f.input :quota_messages,  :label => t('.quota_messages'), :hint => t('.no_limit')

  .actions
    = f.button :button, t('.submit'), :type => 'submit', :class => 'btn-primary right'
    = f.button :button, t('.reset'), :type => 'reset', :class => 'left'

app/views/users/_templates.html.haml
%script#vusers_each_EJS{"type" => "text/ejs"}
  :plain
    <% list (items, function(item, index) { %>
      <tr id="user_<%= index %>">
  %td
    %i.icon-inbox
    :plain
      <%= item.email %>@<%= domain_name %>
  %td
    %i.icon-user
    :plain
      <%= item.name %>
  %td.tar
    = link_to t(".edit"), edit_domain_user_path('{domain_id}', '{id}'), :class => 'label edit-user'
    = link_to "&times;".html_safe, domain_user_path('{domain_id}', '{id}'), :class => 'rm-user', :title => t(".delete")

  :plain
      </tr>
    <% }) %>

%script#vusers_tabr_EJS{"type" => "text/ejs"}
  %tr.new

%script#vusers_form_EJS{"type" => "text/ejs"}
  %td{:colspan => "4"}
    = render :partial => '/users/form', :locals => { :virtual_user => user_ejs_object }