config/routes.rb
Rmails::Application.routes.draw do

  devise_for :admin_users, :skip => :registrations

  resources :admin_users, :only => [:index, :create, :update]
  match 'admin_users/first' => 'admin_users#first',
             :as => 'first_admin_user'

  resources :domains do
    resources :users
    resources :aliases
  end

  match 'server' => 'server#index',
             :as => 'server'
  match 'server/config/:id' => 'server#property',
             :as => 'server_property'
  match 'server/save_config' => 'server#update',
             :as => 'server_update'

  match 'statistics' => 'statistics#index',
             :as => 'statistics'

  devise_scope :admin_user do
    root :to => "devise/sessions#new"
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable,
         :validatable, :lockable

  has_and_belongs_to_many :virtual_domains, :join_table => :users_domains

  attr_accessible :name, :email, :password, :password_confirmation, :virtual_domain_ids

  attr_accessor :password_confirmation

  validates :email,
    :presence   => true,
    :uniqueness => true,
    :format     => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  #validates :password,
  #  :presence   => true,
  #  :unless     => 'selfpassword.empty?'

  before_create :be_super!, :if => 'AdminUser.first.nil?'

  def be_super!
    self.super = true
  end

  def domains
    vd = self.super == true ? VirtualDomain.all : self.virtual_domains
    vd.each do |domain|
      VirtualUser.drop_domain_from_email_each(domain.virtual_users)
    end
    vd
  end

  def domain(id)
    (self.super == true ? VirtualDomain : self.virtual_domains).find(id)
  end

  def build_domain(params)
    domain = self.virtual_domains.build
    domain[:name] = params[:name]
    domain
  end


  def change_data(params)
    attrs = params.symbolize_keys
    if attrs[:password].blank?
      attrs.delete(:password)
      update_without_password(attrs)
    else
      update_with_password(attrs)
    end
  end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  def index
    @admins = AdminUser.includes(:virtual_domains)
  end


  def first
    @admin = AdminUser.new
  end

  def create # JSON or HTML
    @admin = AdminUser.new(params[:admin_user])
    if @admin.save
      respond_to do |format|
        format.json { render :json => {:id => @admin.id} }
        format.html {
          flash[:success] = t('first_admin_user_success')
          #respond_with @admin, :location => domains_path
          sign_in(@admin, :bypass => true)
          redirect_to domains_path
        }
      end
    else
      respond_to do |format|
        format.json { render :json => {:errors => @admin.errors } }
        format.html {
          flash[:error] = t('first_admin_user_error')
          render :action => 'first'
        }
      end
    end
  end

  def update # JSON only
    @admin = AdminUser.find(params[:id])
    if  @admin == current_admin_user or current_admin_user.super
      if @admin.change_data params
        render :json => {:id => @admin.id}
      else
        render :json => {:errors => @admin.errors}
      end
    else
      render :json => {:errors => t('not_authorized')}
    end
  rescue
    render :json => {:errors => t('unknown_error')}
  end


  def destroy # JSON only
    if current_admin_user.super
      AdminUser.find(params[:id]).destroy
      render :json => {:id => nil}
    else
      render :status => 405
    end
  rescue
    render :status => 404
  end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper

  def admin_ejs_object
    AdminUser.new({
      #:super => "<%= item.super %>".html_safe,
      :email    => "<%= item.email %>".html_safe,
      :name => "<%= item.name %>".html_safe
    })
  end

end

app/views/admin_users/_form.html.haml
= simple_form_for admin, :url => admin_users_path, :method => :post, :html => { :class => 'form-horizontal' } do |f|

  .span4.edit
    %h4=t '.infos'
    = f.input :name, :label => t('.name')
    = f.input :email, :label => t('.email')
    = f.input :password
    = f.input :password_confirmation

    -#= f.input :super, :as => :check_box, :label => t('.super')

  .span5.domains
    %h4=t '.domains'
    = f.collection_select :virtual_domain_ids, VirtualDomain.all,
                          :id, :name,
                          {},
                          {:multiple => true}
  .out

    = f.button :button, t('.create'), :type => 'submit', :class => 'btn-primary'
    = f.button :button, t('.reset'), :type => 'reset'

app/views/admin_users/first.html.haml
- content_for :title do
  &rarr;
  = t('.first_admin_user')

= simple_form_for @admin, :url => admin_users_path, :method => :post, :html => { :class => 'form-horizontal' } do |f|

  = f.input :name, :label => t('.name')
  = f.input :email, :label => t('.email')
  = f.input :password, :label => t('.pass'), :required => true

  = f.button :button, t('.create'), :type => 'submit', :class => 'btn-primary'

app/views/admin_users/index.html.haml
- content_for :title do
  &rarr;
  = t('.title')
- content_for :script do
  :javascript
    $(document).ready(function() { new window.Admins('#content'); });

= link_to admin_users_path, :class => 'add-admin btn btn-large btn-inverse' do
  %span= t '.create'

%ul#admins.list
  - @admins.each do |admin|
    %li{:id => "admin_#{admin.id}"}
      .item
        %i.icon-user.icon-large
        .item-content
          = link_to admin.name||admin.email, admin_user_path(admin), :class => 'item-label'
          = link_to t(".manage"), admin_user_path(admin), :class => 'label label-info manage', :'data-inverse' => t(".nomanage")


#admins_JSON.dn= @admins.to_json(:include => :domains)


#EJS.dn
  %script#admin_form_EJS{"type" => "text/ejs"}
    %li.empty
      .item
        %i.icon-user.icon-large
        .item-content
          = t('.new_user')
        .item-content.out.row-fluid
          = render :partial => 'form', :locals => { :admin => admin_ejs_object }
        .out

  %script#admin_item_EJS{"type" => "text/ejs"}
    %i.icon-user.icon-large
    .item-content
      %a{:href => "", :class => "item-label"}
        :plain
          <% if(item.name) { %>
            <%= item.attr('name') %>
          <% } else { %>
            <%= item.attr('email') %>
          <% } %>
      = link_to t(".manage"), admin_user_path('{id}'), :class => 'label label-info manage', :'data-inverse' => t(".nomanage")

  %script#errors_EJS{"type" => "text/ejs"}
    .errors
      %h6= t('.errors')
      :plain
        <% for (attr in errors) { %>
          <% list (errors[attr], function(error) { %>
            <p><%= error %></p>
          <% }) %>
        <% } %>

  %script#manage_area_EJS{"type" => "text/ejs"}
    .item-content.out.row-fluid
      = render :partial => 'form',
                 :locals => { :admin => admin_ejs_object }