config/routes.rb
Rmails::Application.routes.draw do

  devise_for :admin_users, :skip => :registrations

  resources :admin_users, :only => [:index, :create, :update]
  match 'admin_users/first' => 'admin_users#first',
             :as => 'first_admin_user'

  resources :domains do
    resources :users
    resources :aliases
  end

  match 'server' => 'server#index',
             :as => 'server'
  match 'server/config/:id' => 'server#property',
             :as => 'server_property'
  match 'server/save_config' => 'server#update',
             :as => 'server_update'

  match 'statistics' => 'statistics#index',
             :as => 'statistics'

  devise_scope :admin_user do
    root :to => "devise/sessions#new"
  end

end

app/views/layouts/_nav.html.haml
%li= link_to t("navigation.domains"), domains_path, :class => current_page?(domains_path) ? 'active' : ''
%li= link_to t("navigation.server_settings"), server_path, :class => current_page?(server_path) ? 'active' : ''
%li= link_to t("navigation.admins"), admin_users_path, :class => current_page?(admin_users_path) ? 'active' : ''
%li= link_to t("navigation.statistics"), statistics_path, :class => current_page?(statistics_path) ? 'active' : ''

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title Mails on Rails
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body#rmails
    %header
      %h1.left
        = link_to 'RMails', root_url
        = yield :title
      - if current_admin_user
        %span.right
          = t('loggedin')
          = current_admin_user.email
          %br
          = link_to t('logout'), destroy_admin_user_session_path, :method => :delete

    .body-wrapper.out
      .left-column
        .left-column-content
          %ul.navigation
            = render :partial => '/layouts/nav'
      .center-column
        #content.center-column-content
          = yield
      .right-column
    = yield :script